---
- name: Jinja2 default filters
  hosts: localhost
  gather_facts: False

  tasks:

    # If sleeptime is not defined, the integer value of 45 will be used
    # rather than raising an error. Pausing a playbook is sometimes necessary
    # in networking plays to prevent racing.
    - name: Jinja2 default filter - example
      pause:
        seconds: "{{ sleeptime | default(45) }}"

    # If you want to use the default value when vars evaluate to false or an empty string
    # then you have to set a second parameter to true
    - name: Jinja2 default filter - example
      debug:
        msg: "Prevent undefined var err {{ myvariable | default('by setting a default', true) }}"
  vars:
    my_list:
    - "1) A hyphen represents an item on a list"
    - "2) So the second item on the list is this"
    - "3) Whereas this would be the third"
    - "4) Item var is always replaced by an item from the loop list"
  tasks:
   - name: "Learning about the debug module"
     ansible.builtin.debug:
       msg: "Debug module allows us to print to the screen --> {{ item }}"
     loop: "{{ my_list }}"
